#!/bin/bash

echo "🚀 상담센터 플랫폼 수동 실행"
echo ""
echo "다음 명령어들을 각각 다른 터미널에서 실행하세요:"
echo ""
echo "1. API 서버 (터미널 1):"
echo "   cd apps/api && npm install && npm run start:dev"
echo ""
echo "2. 웹 앱 (터미널 2):"
echo "   cd apps/web && npm install && npm run dev"
echo ""
echo "3. 관리자 콘솔 (터미널 3):"
echo "   cd apps/admin && npm install && npm run dev"
echo ""
echo "📱 접속 주소:"
echo "   웹 앱:        http://localhost:3000"
echo "   관리자 콘솔:  http://localhost:3002"
echo "   API 서버:     http://localhost:3001"
echo ""
echo "각 터미널에서 Ctrl+C로 중지할 수 있습니다."
